name: Build Image

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/maa123/rust-builder/rust-linux-amd64

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: amd64
            platform: linux/amd64
            runs_on: ubuntu-24.04
          - name: arm64
            platform: linux/arm64
            runs_on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs_on }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive temp tag
        id: tmp
        run: |
          echo "tmp_tag=${{ env.IMAGE_NAME }}:tmp-${{ github.sha }}-${{ matrix.name }}" >> $GITHUB_OUTPUT

      - name: Build & push (native)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.tmp.outputs.tmp_tag }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save digest
        run: |
          echo "${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}" > digest-${{ matrix.name }}.txt

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ matrix.name }}
          path: digest-${{ matrix.name }}.txt
          retention-days: 1

  merge:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: digests
          pattern: digest-*
          merge-multiple: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive final tags
        id: tags
        run: |
          REPO="${{ env.IMAGE_NAME }}"
          TAGS="${REPO}:sha-${GITHUB_SHA::7}"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAGS="${TAGS},${REPO}:${GITHUB_REF_NAME},${REPO}:latest"
          elif [[ "${GITHUB_REF_TYPE}" == "branch" ]]; then
            BRANCH="${GITHUB_REF_NAME##*/}"
            TAGS="${TAGS},${REPO}:${BRANCH}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Create and push multi-arch manifest
        run: |
          A="${{ env.IMAGE_NAME }}@$(cat digests/digest-amd64.txt)"
          B="${{ env.IMAGE_NAME }}@$(cat digests/digest-arm64.txt)"
          docker buildx imagetools create \
            -t $(echo "${{ steps.tags.outputs.tags }}" | tr ',' ' -t ') \
            "$A" "$B"