name: Build Image

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/maa123/rust-builder/rust-linux-amd64

jobs:
  docker-build:
    runs-on: ${{ matrix.runner_platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner_platform:
          - { runner: ubuntu-24.04,     platform: linux/amd64, architecture: amd64 }
          - { runner: ubuntu-24.04-arm, platform: linux/arm64, architecture: arm64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (native)
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.runner_platform.platform }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
          outputs: type=image,name=${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          set -euo pipefail
          mkdir -p /tmp/digests/${{ matrix.runner_platform.architecture }}/
          digest="${{ steps.docker_build.outputs.digest }}"
          touch "/tmp/digests/${{ matrix.runner_platform.architecture }}/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.runner_platform.architecture }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-manifests:
    needs: [docker-build]
    runs-on: ubuntu-24.04
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          set -euo pipefail
          digest_amd64=$(ls amd64)
          digest_arm64=$(ls arm64)

          docker buildx imagetools create \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            ${{ env.IMAGE_NAME }}@sha256:${digest_amd64} \
            ${{ env.IMAGE_NAME }}@sha256:${digest_arm64}
